/** Checked-in product copy. Keys are stable; Arabic is local Modern Standard Arabic, never a network translation. */
export const messages = {
  'settings.sourceHeading': ['Data source', 'مصدر البيانات'],
  'settings.deviceHeading': ['On this device', 'على هذا الجهاز'],
  'settings.mockSourceHelp': ['Development readings · no wearable connection', 'قراءات تجريبية · دون اتصال بسوار'],
  'settings.huaweiSourceHelp': ['Steps only · broader access pending', 'الخطوات فقط · الوصول لبقية القراءات قيد الانتظار'],
  'dev.buildLabel': ['Development build', 'نسخة تطوير'],
  'today.modelDetails': ['Weights and personal ranges', 'الأوزان والنطاقات الشخصية'],
  'today.signalsUsed': ['{count} of 3 signals', '{count} من 3 مؤشرات'],
  'movement.selectedA11y': ['Selected day {date}. {readings}', 'اليوم المحدد {date}. {readings}'],
  'today.focusShortcut': ['Open this measurement’s details', 'فتح تفاصيل هذا القياس'],
  'today.mockDisclosure': ['Development examples only. These readings are synthetic, not live Huawei wearable data.', 'أمثلة للتطوير فقط. هذه القراءات اصطناعية وليست بيانات مباشرة من جهاز Huawei.'],
  'today.huaweiStepOnly': ['Huawei access currently supports steps only. Other measurements remain unavailable while broader Health Service Kit approval and integration are pending.', 'يقتصر وصول Huawei حاليًا على الخطوات. تظل القياسات الأخرى غير متاحة إلى حين الموافقة على نطاق أوسع من Health Service Kit وإتمام التكامل.'],
  'today.refreshAvailable': ['You can refresh the selected day now. Saved readings remain available if sync cannot finish.', 'يمكنك تحديث اليوم المحدد الآن. تظل القراءات المحفوظة متاحة إذا تعذرت المزامنة.'],
  'today.refreshBusy': ['An update is already in progress.', 'جارٍ تحديث البيانات بالفعل.'],
  'today.refreshUnavailable': ['Refresh will be available when a day is selected.', 'يتاح التحديث بعد تحديد يوم.'],
  'nav.today': ['Today', 'اليوم'], 'nav.trends': ['Trends', 'الاتجاهات'], 'nav.insights': ['Insights', 'الملاحظات'], 'nav.settings': ['Settings', 'الإعدادات'],
  'brand.short': ['Health Analytics', 'تحليلات الصحة'], 'brand.full': ['Huawei Health Analytics', 'Huawei Health Analytics'],
  'metric.recovery': ['Recovery', 'التعافي'], 'metric.sleep': ['Sleep', 'النوم'], 'metric.sleepDuration': ['Sleep duration', 'مدة النوم'],
  'metric.hrv': ['HRV', 'HRV'], 'metric.hrvFull': ['Heart rate variability', 'تباين معدل ضربات القلب'],
  'metric.rhr': ['RHR', 'RHR'], 'metric.rhrFull': ['Resting heart rate', 'نبض الراحة'], 'metric.oxygen': ['Oxygen saturation', 'تشبع الأكسجين'],
  'metric.spo2': ['SpO₂', 'SpO₂'], 'metric.stress': ['Stress', 'التوتر'], 'metric.activity': ['Activity', 'النشاط'], 'metric.steps': ['Steps', 'الخطوات'],
  'metric.activityFull': ['Activity and steps', 'النشاط والخطوات'], 'metric.stepsLower': ['steps', 'خطوة'],
  'common.history': ['History', 'السجل'], 'common.average': ['Average', 'المتوسط'], 'common.median': ['Median', 'الوسيط'],
  'common.latest': ['Latest', 'الأحدث'], 'common.latestDay': ['Latest day', 'أحدث يوم'], 'common.coverage': ['Coverage', 'توفر البيانات'],
  'common.recordedDays': ['Recorded days', 'أيام مسجلة'], 'common.personalRange': ['Personal range', 'نطاقك المعتاد'],
  'common.baseline': ['Baseline', 'خط الأساس'], 'common.cancel': ['Cancel', 'إلغاء'], 'common.save': ['Save', 'حفظ'],
  'common.delete': ['Delete', 'حذف'], 'common.edit': ['Edit', 'تعديل'], 'common.details': ['Details', 'التفاصيل'],
  'common.retry': ['Try again', 'حاول مجددًا'], 'common.close': ['Close sheet', 'إغلاق النافذة'], 'common.back': ['Go back', 'رجوع'],
  'common.noReading': ['No reading', 'لا توجد قراءة'], 'common.noDayReading': ['No reading on this day', 'لا توجد قراءة لهذا اليوم'],
  'common.noTodayReading': ['No reading today', 'لا توجد قراءة اليوم'], 'common.noData': ['No data', 'لا توجد بيانات'],
  'common.unavailable': ['Unavailable', 'غير متاح'], 'common.notAvailable': ['Not available', 'غير متاح'], 'common.notReported': ['Not reported', 'لم يُسجّل'],
  'common.readingFailed': ['Reading failed', 'تعذر جلب القراءة'], 'common.readingUnavailable': ['Reading unavailable', 'القراءة غير متاحة'],
  'common.noUsableData': ['No usable data', 'لا توجد بيانات صالحة'], 'common.loading': ['Loading…', 'جارٍ التحميل…'],
  'common.updating': ['Updating…', 'جارٍ التحديث…'], 'common.notScored': ['Not scored', 'لم تُحسب'], 'common.learning': ['Learning', 'جارٍ تعلم نمطك'],
  'common.viewDetails': ['View details.', 'عرض التفاصيل.'], 'common.browser': ['Opens in your browser', 'يفتح في المتصفح'],
  'today.state': ['Today’s Recovery', 'تعافيك اليوم'], 'today.focus': ['Your shortcuts', 'اختصاراتك'], 'today.night': ['Your night', 'ليلتك'],
  'today.signals': ['Signals', 'المؤشرات'], 'today.movement': ['Movement', 'الحركة'], 'today.pattern': ['Worth noticing', 'يستحق الملاحظة'],
  'today.week': ['This week', 'هذا الأسبوع'], 'today.openWeek': ['Open seven-day snapshot', 'عرض ملخص آخر سبعة أيام'],
  'today.customize': ['Customize Today', 'تخصيص اليوم'], 'today.customizeHelp': ['Emphasize up to three readings. Recovery stays at the top.', 'اختر حتى ثلاثة مؤشرات لإبرازها. يبقى التعافي في المقدمة.'],
  'today.save': ['Save Today', 'حفظ التخصيص'], 'today.saving': ['Saving…', 'جارٍ الحفظ…'], 'today.freshness': ['View data freshness', 'عرض آخر تحديث للبيانات'],
  'today.data': ['Your data', 'بياناتك'], 'today.shape': ['What shaped your score', 'ما الذي شكّل نتيجتك؟'],
  'today.less': ['Less −', 'أقل −'], 'today.why': ['Why +', 'السبب +'], 'today.explore': ['Explore Recovery ›', 'استكشف التعافي ‹'],
  'today.learning': ['Getting to know you', 'نتعرف على نمطك'], 'today.notEnough': ['Not enough signals', 'المؤشرات غير كافية'],
  'today.reference': ['Your personal reference', 'مرجعك الشخصي'], 'today.opening': ['Opening your day', 'جارٍ فتح بيانات يومك'],
  'today.syncAttention': ['Sync needs attention', 'تعذر إكمال المزامنة'], 'today.dataUnavailable': ['Data unavailable', 'البيانات غير متاحة'],
  'today.noReadings': ['No readings yet', 'لا توجد قراءات بعد'], 'today.syncHelp': ['Sync a day to see your personal signals here.', 'زامن بياناتك لعرض مؤشراتك هنا.'],
  'today.openHistory': ['Open history', 'فتح السجل'], 'today.syncNow': ['Sync now', 'المزامنة الآن'], 'today.allTrends': ['All trends', 'كل الاتجاهات'],
  'today.weekGlance': ['Your week at a glance', 'أسبوعك في لمحة'], 'today.weekContext': ['See your recent readings together.', 'اطّلع على قراءاتك الأخيرة معًا.'],
  'today.weekNeedsData': ['A week needs readings', 'نحتاج إلى قراءات الأسبوع'], 'today.weekAfterSync': ['Your recent summary appears after data is synced.', 'يظهر ملخصك بعد مزامنة البيانات.'],
  'today.strongest': ['Strongest observation', 'أبرز ملاحظة'], 'today.weekHelp': ['Your last seven days with data', 'آخر سبعة أيام من بياناتك'],
  'today.noTiming': ['Timing not recorded', 'الأوقات غير مسجلة'], 'today.sleepScore': ['Sleep score', 'نتيجة النوم'],
  'today.active': ['Active', 'دقائق النشاط'], 'today.energy': ['Energy', 'الطاقة'], 'today.workouts': ['Workouts', 'التمارين'],
  'state.syncNeeded': ['Sync needed', 'يلزم التزامن'], 'state.mock': ['Mock data', 'بيانات تجريبية'], 'state.mockSynthetic': ['Synthetic mock data', 'بيانات تجريبية اصطناعية'],
  'state.cached': ['Cached data', 'بيانات محفوظة'], 'state.updatedNow': ['Updated now', 'تم التحديث الآن'], 'state.updating': ['Updating', 'جارٍ التحديث'],
  'state.notSynced': ['Not synced yet', 'لم تتم المزامنة بعد'], 'state.refreshing': ['Refreshing…', 'جارٍ التحديث…'],
  'state.refreshFailed': ['Last refresh failed', 'تعذر آخر تحديث'], 'state.updatedJustNow': ['Updated just now', 'تم التحديث للتو'],
  'state.notSupported': ['Not supported by this source', 'غير مدعوم من هذا المصدر'], 'state.noPersonalRange': ['No personal range', 'لا يتوفر نطاق شخصي'],
  'state.inRange': ['Within your range', 'ضمن نطاقك المعتاد'], 'state.noUsableReading': ['No usable reading', 'لا توجد قراءة صالحة'],
  'state.noCoverage': ['Not enough coverage for the previous-period comparison', 'البيانات غير كافية للمقارنة بالفترة السابقة'],
  'state.noBedtimeComparison': ['Not enough bedtime data for a consistency comparison', 'أوقات النوم غير كافية لمقارنة الانتظام'],
  'calendar.title': ['Your history', 'سجلك'], 'calendar.previous': ['Previous month', 'الشهر السابق'], 'calendar.next': ['Next month', 'الشهر التالي'],
  'calendar.previousDay': ['Previous recorded day', 'اليوم المسجل السابق'], 'calendar.nextDay': ['Next recorded day', 'اليوم المسجل التالي'],
  'calendar.today': ['Jump to Today', 'الانتقال إلى اليوم'], 'calendar.choose': ['Choose month', 'اختر الشهر'],
  'trends.eyebrow': ['YOUR SIGNALS OVER TIME', 'مؤشراتك عبر الوقت'], 'trends.updating': ['Updating history', 'جارٍ تحديث السجل'],
  'trends.preparing': ['Preparing history', 'جارٍ إعداد السجل'], 'trends.saved': ['Showing saved history', 'نعرض السجل المحفوظ'],
  'trends.unavailable': ['History unavailable', 'السجل غير متاح'], 'trends.noHistory': ['No history yet', 'لا يوجد سجل بعد'],
  'trends.syncHelp': ['Sync your health data to start exploring.', 'زامن بياناتك لبدء استكشاف السجل.'],
  'trends.measurement': ['MEASUREMENT', 'المؤشر'], 'trends.compareWith': ['COMPARE WITH', 'قارن مع'],
  'trends.choose': ['Choose a measurement', 'اختر مؤشرًا'], 'trends.comparePicker': ['Compare with', 'قارن مع'],
  'trends.openPicker': ['Opens the measurement list', 'يفتح قائمة المؤشرات'], 'trends.openPickerOld': ['Opens the measurement list', 'يفتح قائمة المؤشرات'],
  'trends.scaleHelp': ['Each measurement keeps its own scale and unit.', 'لكل مؤشر مقياسه ووحدته.'],
  'trends.compare': ['Compare', 'مقارنة'], 'trends.endCompare': ['End comparison', 'إنهاء المقارنة'],
  'trends.compareNote': ['Independent scales. Compare patterns, not heights. Association does not show cause.', 'المقياسان مستقلان. قارن الأنماط لا ارتفاع الخطوط. التزامن لا يعني السببية.'],
  'trends.glance': ['Period at a glance', 'الفترة في لمحة'], 'trends.shaded': ['Shaded band · personal range', 'المساحة المظللة · نطاقك المعتاد'],
  'trends.sleepTiming': ['SLEEP TIMING', 'أوقات النوم'], 'chart.touch': ['Touch the chart to explore', 'المس الرسم لاستكشاف القراءات'],
  'chart.noReadings': ['No readings in this period', 'لا توجد قراءات في هذه الفترة'], 'chart.noSecondary': ['No reading this day', 'لا توجد قراءة لهذا اليوم'],
  'chart.hint': ['Drag to inspect a day. Swipe up or down with a screen reader to move between recorded days.', 'اسحب لاستعراض يوم. مع قارئ الشاشة، اسحب لأعلى أو لأسفل للتنقل بين الأيام المسجلة.'],
  'insights.eyebrow': ['YOUR PATTERNS', 'أنماطك'], 'insights.preparing': ['Finding your patterns', 'جارٍ استعراض أنماطك'],
  'insights.noChange': ['No notable change', 'لا تغير ملحوظ'], 'insights.noWeekChange': ['No clear observation in the last seven days.', 'لا توجد ملاحظة واضحة في آخر سبعة أيام.'],
  'insights.observations': ['Observations', 'الملاحظات'], 'insights.week': ['Weekly summary', 'ملخص الأسبوع'],
  'insights.averageRecovery': ['Average Recovery', 'متوسط التعافي'], 'insights.averageSleep': ['Average Sleep', 'متوسط النوم'],
  'insights.timing': ['Sleep timing', 'أوقات النوم'], 'insights.consistency': ['Consistency', 'الانتظام'], 'insights.periodChange': ['Period change', 'تغير خلال الفترة'],
  'detail.signals': ['YOUR SIGNALS', 'مؤشراتك'], 'detail.opening': ['Opening history', 'جارٍ فتح السجل'],
  'detail.scoreShape': ['What shaped this score', 'ما الذي شكّل هذه النتيجة؟'], 'detail.insideNight': ['Inside your night', 'تفاصيل ليلتك'],
  'detail.reference': ['Your personal reference', 'مرجعك الشخصي'], 'detail.restingRhythm': ['Resting rhythm', 'نبضك في الراحة'],
  'detail.observationRange': ['Observation range', 'نطاق القراءات'], 'detail.context': ['Your daily context', 'سياق يومك'],
  'detail.movement': ['Movement in context', 'الحركة في سياقها'], 'detail.dayUnavailable': ['Day unavailable', 'بيانات اليوم غير متاحة'],
  'detail.readingDay': ['Reading this day', 'جارٍ فتح بيانات اليوم'], 'detail.recent': ['Recent readings', 'القراءات الأخيرة'],
  'detail.tryLonger': ['Try a longer period.', 'جرّب فترة أطول.'], 'detail.returnLatest': ['Return to the latest day in this period', 'العودة إلى أحدث يوم في الفترة'],
  'detail.noScore': ['No score on this day', 'لا توجد نتيجة لهذا اليوم'], 'detail.building': ['Building your baseline', 'جارٍ بناء خط الأساس'],
  'detail.dayContextLoading': ['Loading this day’s context…', 'جارٍ تحميل سياق هذا اليوم…'], 'detail.moreContributors': ['More valid history will reveal your personal contributors.', 'تتيح القراءات الصالحة الإضافية فهم مساهمة مؤشراتك.'],
  'detail.bedtime': ['Bedtime', 'وقت النوم'], 'detail.wake': ['Wake time', 'وقت الاستيقاظ'], 'detail.inBed': ['In bed', 'الوقت في السرير'],
  'detail.low': ['Daily low', 'أقل قراءة يومية'], 'detail.high': ['Daily high', 'أعلى قراءة يومية'], 'detail.dailyAverage': ['Daily average', 'المتوسط اليومي'],
  'detail.observations': ['Observations', 'القراءات'], 'detail.minimum': ['Minimum', 'الأدنى'], 'detail.maximum': ['Maximum', 'الأعلى'],
  'detail.distance': ['Distance', 'المسافة'], 'detail.allHeart': ['All heart-rate readings', 'جميع قراءات النبض'],
  'detail.heartNote': ['These include other contexts and differ from resting heart rate.', 'تشمل هذه القراءات حالات أخرى وتختلف عن نبض الراحة.'],
  'detail.rmssd': ['RMSSD · daily average of your observations', 'RMSSD · المتوسط اليومي لقراءاتك'],
  'detail.stressNote': ['Your source’s stress index · separate from Recovery', 'مؤشر التوتر من مصدر بياناتك · مستقل عن التعافي'],
  'detail.personalReference': ['Personal reference', 'المرجع الشخصي'], 'detail.moreHistory': ['More valid history needed', 'نحتاج إلى سجل صالح أطول'],
  'detail.recentRange': ['Your recent range', 'نطاقك المعتاد مؤخرًا'], 'detail.bedtimeMore': ['More bedtime history needed', 'نحتاج إلى سجل أطول لأوقات النوم'],
  'detail.averageOxygen': ['Average oxygen saturation', 'متوسط تشبع الأكسجين'], 'detail.averageStress': ['Average stress index', 'متوسط مؤشر التوتر'],
  'detail.dailyMovement': ['Your movement for this day', 'حركتك في هذا اليوم'], 'detail.dailySignal': ['Your personal daily signal', 'مؤشرك اليومي الشخصي'],
  'sleep.deep': ['Deep', 'عميق'], 'sleep.rem': ['REM', 'REM'], 'sleep.light': ['Light', 'خفيف'], 'sleep.awake': ['Awake', 'يقظة'], 'sleep.unreported': ['Unreported', 'غير مسجل'],
  'settings.eyebrow': ['YOUR APP', 'تطبيقك'], 'settings.appearance': ['APPEARANCE', 'المظهر'], 'settings.appearanceTitle': ['Appearance', 'المظهر'],
  'settings.theme': ['Theme', 'المظهر'], 'settings.language': ['Language', 'اللغة'], 'settings.english': ['English', 'English'], 'settings.arabic': ['العربية', 'العربية'],
  'settings.system': ['System', 'النظام'], 'settings.dark': ['Dark', 'داكن'], 'settings.light': ['Light', 'فاتح'],
  'settings.systemHelp': ['Follow your device appearance', 'اتبع مظهر الجهاز'], 'settings.darkHelp': ['Deep navy and lavender', 'كحلي داكن ولمسات بنفسجية'],
  'settings.lightHelp': ['Soft lilac and indigo', 'درجات ليلكية ونيلية هادئة'], 'settings.loading': ['Loading settings', 'جارٍ تحميل الإعدادات'],
  'settings.readingPrefs': ['Reading on-device preferences.', 'جارٍ قراءة تفضيلاتك المحفوظة.'], 'settings.failed': ['Couldn’t complete that', 'تعذر إكمال الإجراء'],
  'settings.unavailable': ['Settings unavailable', 'الإعدادات غير متاحة'], 'settings.notificationsHeading': ['NOTIFICATIONS', 'الإشعارات'],
  'settings.notifications': ['Notifications', 'الإشعارات'], 'settings.daily': ['Daily reminder', 'التذكير اليومي'], 'settings.time': ['Reminder time', 'وقت التذكير'],
  'settings.masterA11y': ['Notifications enabled', 'تفعيل الإشعارات'], 'settings.dailyA11y': ['Daily reminder enabled', 'تفعيل التذكير اليومي'],
  'settings.permissionAllowed': ['System permission allowed · reminders use local time.', 'الإذن متاح · يستخدم التذكير الوقت المحلي.'],
  'settings.permissionOff': ['Permission is off', 'الإذن غير مفعّل'], 'settings.ready': ['Ready when you are', 'فعّله عندما تريد'],
  'settings.remindersUnavailable': ['Reminders unavailable', 'التذكيرات غير متاحة'], 'settings.systemSettings': ['Open system settings ↗', 'فتح إعدادات الجهاز ↖'],
  'settings.data': ['DATA', 'البيانات'], 'settings.source': ['Data source', 'مصدر البيانات'], 'settings.authorization': ['Authorization', 'التفويض'],
  'settings.sync': ['Last sync', 'آخر مزامنة'], 'settings.notSynced': ['Not synced', 'لم تتم المزامنة'], 'settings.delete': ['Delete local health data', 'حذف بيانات الصحة المحلية'],
  'settings.local': ['Imported history stays on this device.', 'يبقى السجل المستورد على هذا الجهاز.'], 'settings.development': ['DEVELOPMENT', 'التطوير'],
  'settings.about': ['ABOUT', 'حول التطبيق'], 'settings.privacy': ['Privacy Policy', 'سياسة الخصوصية'], 'settings.terms': ['User Agreement', 'اتفاقية المستخدم'],
  'settings.version': ['Version', 'الإصدار'], 'settings.aboutHelp': ['Personal wellness information, not medical advice. Reminders contain no health data and do not sync in the background.', 'معلومات للرفاهية الشخصية وليست نصيحة طبية. لا تتضمن التذكيرات بيانات صحية ولا تزامنها في الخلفية.'],
  'settings.localTime': ['Uses your device’s local time', 'يستخدم الوقت المحلي لجهازك'], 'settings.deleteTitle': ['Delete local health data?', 'هل تريد حذف بيانات الصحة المحلية؟'],
  'settings.deleteHelp': ['This removes imported health history from this device. App preferences remain.', 'سيُحذف السجل الصحي المستورد من هذا الجهاز. تبقى تفضيلات التطبيق.'],
  'permission.notDetermined': ['Turn on Notifications to allow a daily reminder.', 'فعّل الإشعارات للسماح بالتذكير اليومي.'],
  'permission.denied': ['Enable notifications in system settings to receive reminders.', 'فعّل الإشعارات من إعدادات الجهاز لتلقي التذكيرات.'],
  'permission.unavailable': ['Notifications are unavailable in this environment.', 'الإشعارات غير متاحة في هذه البيئة.'],
  'permission.error': ['System permission couldn’t be read. Return to this screen to retry.', 'تعذر التحقق من إذن الجهاز. عد إلى هذه الشاشة للمحاولة مجددًا.'],
  'authorization.notRequired': ['Not required', 'غير مطلوب'], 'authorization.authorized': ['Authorized', 'مفوّض'], 'authorization.denied': ['Denied', 'مرفوض'],
  'authorization.notRequested': ['Not requested', 'لم يُطلب'], 'sync.running': ['running', 'جارٍ التنفيذ'], 'sync.succeeded': ['succeeded', 'مكتملة'], 'sync.failed': ['failed', 'تعذرت'],
  'dev.tools': ['Developer Tools', 'أدوات التطوير'], 'dev.back': ['‹ Settings', '› الإعدادات'], 'dev.help': ['Selecting a scenario replaces local mock health records.', 'اختيار سيناريو يستبدل بيانات الصحة التجريبية المحلية.'],
  'dev.failed': ['Couldn’t load scenario', 'تعذر تحميل السيناريو'], 'dev.loading': ['Loading scenarios', 'جارٍ تحميل السيناريوهات'],
  'dev.unavailable': ['Unavailable in this build', 'غير متاح في هذه النسخة'], 'dev.requires': ['Scenarios require a development build with mock data.', 'تتطلب السيناريوهات نسخة تطوير ببيانات تجريبية.'],
  'dev.scenarios': ['SCENARIOS', 'السيناريوهات'], 'dev.local': ['LOCAL DATA', 'بيانات محلية'], 'dev.updating': ['Updating scenario', 'جارٍ تحديث السيناريو'],
  'dev.balanced': ['Balanced', 'متوازن'], 'dev.poorSleep': ['Poor Sleep', 'نوم أقل'], 'dev.lowHrv': ['Low HRV + High RHR', 'HRV أقل ونبض راحة أعلى'],
  'dev.highActivity': ['High Activity', 'نشاط مرتفع'], 'dev.insufficient': ['Insufficient History', 'سجل غير كافٍ'], 'dev.missing': ['Missing Data', 'بيانات ناقصة'],
  'dev.balancedHelp': ['Typical sleep, recovery and movement.', 'نوم وتعافٍ وحركة ضمن النمط المعتاد.'], 'dev.sleepHelp': ['A recent week of shorter, later sleep.', 'أسبوع أخير بنوم أقصر ومتأخر.'],
  'dev.hrvHelp': ['Lower HRV with a higher resting heart rate.', 'تباين نبض أقل مع نبض راحة أعلى.'], 'dev.activityHelp': ['More steps, active minutes and workouts.', 'خطوات ودقائق نشاط وتمارين أكثر.'],
  'dev.historyHelp': ['Seven days, with baselines still learning.', 'سبعة أيام مع استمرار تعلم خط الأساس.'], 'dev.missingHelp': ['Missing readings and a failed heart-rate query.', 'قراءات ناقصة وتعذر جلب بعض بيانات النبض.'],
  'error.openDay': ['Your data could not be opened.', 'تعذر فتح بياناتك.'], 'error.day': ['This day could not be opened.', 'تعذر فتح بيانات هذا اليوم.'],
  'error.sync': ['Sync could not finish. Your saved readings are still available.', 'تعذر إكمال المزامنة. ما زالت قراءاتك المحفوظة متاحة.'],
  'error.focus': ['Your Today preferences could not be saved.', 'تعذر حفظ تخصيص اليوم.'], 'error.history': ['History could not be loaded.', 'تعذر تحميل السجل.'],
  'error.settings': ['Settings could not be loaded.', 'تعذر تحميل الإعدادات.'], 'error.notification': ['The notification setting could not be saved.', 'تعذر حفظ إعداد الإشعار.'],
  'error.page': ['The page could not be opened. Check your connection and try again.', 'تعذر فتح الصفحة. تحقق من الاتصال وحاول مجددًا.'],
  'error.systemSettings': ['System settings could not be opened.', 'تعذر فتح إعدادات الجهاز.'], 'error.delete': ['Local health data could not be deleted. Try again.', 'تعذر حذف بيانات الصحة المحلية. حاول مجددًا.'],
  'error.theme': ['Theme preference could not be saved.', 'تعذر حفظ المظهر.'], 'error.language': ['Language preference could not be saved.', 'تعذر حفظ اللغة.'],
  'error.devLoad': ['Developer tools could not be loaded.', 'تعذر تحميل أدوات التطوير.'], 'error.devScenario': ['The development scenario could not be loaded.', 'تعذر تحميل سيناريو التطوير.'],
  'error.dayContext': ['This day could not be loaded.', 'تعذر تحميل بيانات هذا اليوم.'], 'error.syncEmpty': ['Sync your health data to explore your history.', 'زامن بياناتك لاستكشاف سجلك.'],
  'recovery.good': ['Good recovery', 'تعافٍ جيد'], 'recovery.high': ['High recovery', 'تعافٍ مرتفع'], 'recovery.fair': ['Fair recovery', 'تعافٍ متوسط'], 'recovery.low': ['Low recovery', 'تعافٍ منخفض'],
  'recovery.notScored': ['Recovery not scored', 'لم تُحسب نتيجة التعافي'], 'recovery.learning': ['Learning your baseline', 'نتعلم خط الأساس لديك'],
  'recovery.unavailable': ['Recovery unavailable', 'التعافي غير متاح'], 'range.above': ['Above your range', 'أعلى من نطاقك المعتاد'],
  'range.below': ['Below your range', 'أقل من نطاقك المعتاد'], 'range.within': ['Within your range', 'ضمن نطاقك المعتاد'],
  'guide.recovery': ['Recovery compares HRV, resting heart rate, and sleep with your own prior history. Configured weights are HRV 40%, resting heart rate 35%, and sleep 25%. Applied weights adjust when an input is unavailable. Contributor impacts show points relative to a neutral signal. This is personal wellness context, not medical advice.', 'يقارن التعافي تباين النبض ونبض الراحة والنوم بسجلك السابق. الأوزان الأساسية: HRV ‏40%، ونبض الراحة 35%، والنوم 25%. تُعدّل الأوزان المطبقة عند غياب أحد المدخلات. توضح المساهمة الفرق بالنقاط عن مؤشر محايد. هذا سياق شخصي للرفاهية، وليس نصيحة طبية.'],
  'guide.sleep': ['Sleep stages show the proportions supplied by your source, not a reconstructed timeline. Timing uses your recorded timezone. Bedtime consistency describes variation across available bedtimes in the selected period. Personal ranges use history before each selected date.', 'تعرض مراحل النوم النسب الواردة من مصدر بياناتك، لا تسلسلًا زمنيًا مُعاد بناؤه. تُعرض الأوقات وفق المنطقة الزمنية المسجلة. يصف انتظام النوم اختلاف أوقات النوم المتاحة خلال الفترة. يعتمد النطاق الشخصي على الأيام السابقة للتاريخ المحدد.'],
  'guide.hrv': ['HRV is shown as RMSSD in milliseconds. The daily average combines available observations. Compare changes with your own recent range, built from valid days before the selected date. Gaps remain unrecorded.', 'يُعرض تباين النبض بمقياس RMSSD بوحدة ms. يجمع المتوسط اليومي القراءات المتاحة. قارن التغير بنطاقك المعتاد المحسوب من الأيام الصالحة السابقة للتاريخ المحدد. تبقى الفجوات بلا قراءات.'],
  'guide.rhr': ['Resting heart rate uses the daily resting value supplied by your source. Other heart-rate readings may include sleep or activity. Your personal range uses valid prior days and does not define a population health threshold.', 'يعتمد نبض الراحة على القيمة اليومية التي يوردها مصدر بياناتك. قد تشمل قراءات النبض الأخرى النوم أو النشاط. يُحسب نطاقك الشخصي من أيام سابقة صالحة ولا يمثل حدًا صحيًا عامًا.'],
  'guide.spo2': ['This view shows the average, minimum, and maximum oxygen saturation supplied for each day. Observation count describes coverage within the day. Wearable readings are personal wellness information and do not diagnose oxygen or breathing conditions.', 'يعرض هذا القسم متوسط تشبع الأكسجين وأقل وأعلى قراءة يومية. يشير عدد القراءات إلى توفر البيانات في اليوم. قراءات الأجهزة القابلة للارتداء معلومات شخصية للرفاهية وليست لتشخيص مشكلات الأكسجين أو التنفس.'],
  'guide.stress': ['Stress is your source’s daily index. The rail shows the recorded minimum–maximum with an average marker, not population thresholds or a new score. Stress stays outside Recovery V1.', 'التوتر هو المؤشر اليومي من مصدر بياناتك. يعرض الشريط أدنى وأعلى قراءة مسجلة مع علامة للمتوسط، وليس حدودًا عامة أو نتيجة جديدة. لا يدخل التوتر في حساب التعافي V1.'],
  'guide.activity': ['Steps are the primary movement signal. Active minutes, energy, distance, and workout counts appear only when reported by your source. Bar heights compare actual recorded days; no activity goal or movement timeline is invented.', 'الخطوات هي مؤشر الحركة الأساسي. تظهر دقائق النشاط والطاقة والمسافة وعدد التمارين فقط عند توفرها من المصدر. تقارن الأعمدة الأيام المسجلة فعلًا دون اختراع هدف للنشاط أو تسلسل للحركة.'],
  'format.duration': ['{hours}h {minutes}m', '{hours} س {minutes} د'], 'format.days': ['{count} days', 'الأيام: {count}'],
  'format.period': ['{count}-day view', 'عرض بالأيام: {count}'], 'format.dayPeriod': ['{count} day period', 'الفترة بالأيام: {count}'],
  'format.recorded': ['{count} recorded days', 'أيام مسجلة: {count}'], 'format.coverage': ['{available} of {expected} days available', 'الأيام المتاحة: {available} من {expected}'],
  'format.coverageShort': ['{available} / {expected} days', '{available} / {expected} أيام'],
  'format.updatedMinutes': ['Updated {count}m ago', 'تم التحديث منذ {count} د'], 'format.updatedHours': ['Updated {count}h ago', 'تم التحديث منذ {count} س'],
  'format.modelWeight': ['{count}% model', '{count}% أساسي'], 'format.appliedWeight': ['{model}% model · {applied}% applied', '{model}% أساسي · {applied}% مطبق'],
  'format.rangeLearning': ['Learning · {available}/{required} days', 'نتعلم نمطك · {available}/{required} أيام'],
  'format.recoveryInputs': ['{count}% inputs · {signals} signals', '{count}% من المدخلات · {signals} مؤشرات'],
  'format.recoveryCoverage': ['{signals}/3 signals · {count}% coverage', '{signals}/3 مؤشرات · {count}% من البيانات'],
  'format.weekDates': ['{start} – {end} · last seven days', '{start} – {end} · آخر سبعة أيام'],
  'format.source': ['Source: {source}', 'المصدر: {source}'], 'format.savedDays': ['{count} days saved on this device.', 'الأيام المحفوظة على هذا الجهاز: {count}.'],
  'format.calendarHelp': ['{count} recorded days · dots mark saved readings', 'أيام مسجلة: {count} · النقاط تشير إلى القراءات المحفوظة'],
  'format.emptyError': ['The action could not be completed. Try again.', 'تعذر إكمال الإجراء. حاول مجددًا.'],
  'recovery.gauge': ['RECOVERY', 'التعافي'], 'metric.rhrShort': ['Resting HR', 'نبض الراحة'],
  'insights.notice': ['NOTICE THE PATTERN', 'لاحظ النمط'], 'insights.checking': ['Checking recent history.', 'جارٍ استعراض السجل الأخير.'],
  'insights.refreshFailed': ['Couldn’t refresh', 'تعذر التحديث'], 'insights.unavailable': ['Insights unavailable', 'الملاحظات غير متاحة'],
  'insights.syncHelp': ['Sync your health data to find personal patterns.', 'زامن بياناتك للتعرف على أنماطك.'],
  'insights.noPattern': ['Your readings don’t show a clear pattern for this period.', 'لا تُظهر قراءاتك نمطًا واضحًا في هذه الفترة.'],
  'insights.openWeekly': ['Open weekly summary', 'فتح ملخص الأسبوع'], 'insights.yourWeekly': ['Your weekly summary', 'ملخص أسبوعك'],
  'insights.weekPattern': ['This week’s pattern', 'نمط هذا الأسبوع'], 'error.insights': ['Insights could not be loaded.', 'تعذر تحميل الملاحظات.'],
  'state.sourceUnsupported': ['Not supported by this data source', 'غير مدعوم من مصدر البيانات'], 'state.loadFailed': ['Unable to load', 'تعذر التحميل'],
  'baseline.sourceUnavailable': ['Baseline unavailable for this source', 'لا يتوفر خط أساس من هذا المصدر'],
  'baseline.needsHistory': ['Baseline needs valid history', 'يحتاج خط الأساس إلى سجل صالح'], 'baseline.inRange': ['Within your recent range', 'ضمن نطاقك المعتاد مؤخرًا'],
  'baseline.referenceHelp': ['Valid history will build your personal reference range.', 'يبني السجل الصالح نطاقك المرجعي الشخصي.'],
  'recovery.twoNeeded': ['At least two current signals are needed.', 'نحتاج إلى مؤشرين متاحين على الأقل.'],
  'recovery.sourceInsufficient': ['This source does not provide enough required signals.', 'لا يوفر هذا المصدر مؤشرات مطلوبة كافية.'],
  'recovery.waitBaseline': ['Recovery will appear after enough personal baselines are ready.', 'يظهر التعافي عندما تكتمل خطوط أساس شخصية كافية.'],
  'recovery.fewerTwo': ['Recovery is unavailable because fewer than two signals can be evaluated today.', 'التعافي غير متاح لأن عدد المؤشرات القابلة للتقييم اليوم أقل من اثنين.'],
  'recovery.allInRange': ['Available recovery signals were within their recent personal ranges.', 'كانت مؤشرات التعافي المتاحة ضمن نطاقاتها الشخصية المعتادة مؤخرًا.'],
  'recovery.otherSignals': ['Other available signals stayed within or above their recent pattern.', 'بقيت المؤشرات الأخرى المتاحة ضمن نمطها المعتاد مؤخرًا أو أعلى منه.'],
  'format.readingSteps': ['{amount} steps', '{amount} خطوة'], 'format.readingPoints': ['{amount} points', '{amount} نقطة'],
  'format.snapshot': ['{count}-day snapshot', 'ملخص الأيام: {count}'], 'format.weekSeven': ['{dates} · last 7 calendar days', '{dates} · آخر ٧ أيام تقويمية'],
  'format.weekPeriod': ['{dates} · 7 days', '{dates} · ٧ أيام'], 'format.countDays': ['{count} days', 'الأيام: {count}'],
  'format.compactCoverage': ['{available}/{expected} days', '{available}/{expected} أيام'],
  'format.periodValue': ['{count}-day {aggregation}', '{aggregation} الأيام: {count}'],
  'format.periodAggregation': ['Period {aggregation}', '{aggregation} الفترة'],
  'format.aggregationCoverage': ['{aggregation} · {available}/{expected} days', '{aggregation} · {available}/{expected} أيام'],
  'format.previous': ['VS PREVIOUS {count} DAYS', 'مقارنةً بالأيام السابقة: {count}'],
  'format.recentAverage': ['{value} recent average', '{value} المتوسط الأخير'],
  'format.stable': ['Stable versus the previous {days} days', 'مستقر مقارنةً بالأيام السابقة: {days}'],
  'format.higher': ['{value} higher than the previous period', 'أعلى بمقدار {value} من الفترة السابقة'],
  'format.lower': ['{value} lower than the previous period', 'أقل بمقدار {value} من الفترة السابقة'],
  'format.rangeDelta': ['{value} vs usual', '{value} مقارنةً بالمعتاد'], 'format.change': ['{value} vs previous period', '{value} مقارنةً بالفترة السابقة'],
  'format.learningBaseline': ['Learning baseline - {available} of {required} valid days', 'نتعلم خط الأساس · أيام صالحة: {available} من {required}'],
  'format.baselineDays': ['{available} of {required} valid days across required signals.', 'أيام صالحة عبر المؤشرات المطلوبة: {available} من {required}.'],
  'format.typical': ['Typical {range} · {count} valid days', 'المعتاد {range} · أيام صالحة: {count}'],
  'format.hrvBelow': ['{amount}% below your recent baseline', '{amount}% أقل من خط الأساس الأخير'],
  'format.hrvAbove': ['{amount}% above your recent baseline', '{amount}% أعلى من خط الأساس الأخير'],
  'format.sleepShorter': ['{value} shorter than your recent baseline', 'أقصر بـ {value} من خط الأساس الأخير'],
  'format.sleepLonger': ['{value} longer than your recent baseline', 'أطول بـ {value} من خط الأساس الأخير'],
  'format.rhrBelow': ['{amount} bpm below your recent baseline', '{amount} bpm أقل من خط الأساس الأخير'],
  'format.rhrAbove': ['{amount} bpm above your recent baseline', '{amount} bpm أعلى من خط الأساس الأخير'],
  'format.validDays': ['{count} valid days', 'أيام صالحة: {count}'], 'format.baselineDaysBefore': ['Range from the {count} days before this date', 'النطاق من الأيام السابقة لهذا التاريخ: {count}'],
  'format.personalLearning': ['{available} of {required} valid days · learning your range', 'نتعلم نطاقك · أيام صالحة: {available} من {required}'],
  'format.configuredWeight': ['{count}% configured', '{count}% أساسي'],
  'format.configuredApplied': ['{count}% configured · {applied}% applied', '{count}% أساسي · {applied}% مطبق'],
  'format.impact': ['{amount} pts vs neutral', '{amount} نقطة مقارنةً بالمحايد'], 'format.points': ['{amount} pts', '{amount} نقطة'],
  'format.understand': ['Understand {metric}', 'فهم {metric}'], 'format.baseline': ['Baseline {value}', 'خط الأساس {value}'],
  'format.usual': ['Usual {range} · {relation}', 'المعتاد {range} · {relation}'],
  'format.usualCenter': ['Usual {range} · baseline {centerValue} · {relation}', 'المعتاد {range} · خط الأساس {centerValue} · {relation}'],
  'format.bedtimeCount': ['{count} days with bedtime data', 'أيام بأوقات نوم مسجلة: {count}'],
  'format.bedtimePeriod': ['Bedtime consistency · {count} days', 'انتظام أوقات النوم · الأيام: {count}'],
  'format.bedtimeVariation': ['{amount} min typical variation', '{amount} د اختلاف معتاد'],
  'format.oxygenCount': ['{count} oxygen-saturation observations', 'قراءات تشبع الأكسجين: {count}'],
  'format.observationDay': ['Selected reading {value}', 'القراءة المحددة {value}'],
  'format.dailySteps': ['Daily steps · {dates}', 'الخطوات اليومية · {dates}'],
  'format.recoveryA11y': ['Recovery {count} out of 100', 'التعافي {count} من ١٠٠'],
  'format.stressA11y': ['Stress daily average {count} out of 100', 'متوسط التوتر اليومي {count} من ١٠٠'],
  'format.openDetail': ['Open {metric} details', 'فتح تفاصيل {metric}'],
  'format.historyA11y': ['{metric} history', 'سجل {metric}'],
  'format.closeSheet': ['Close {name}', 'إغلاق {name}'], 'format.openCalendar': ['{date}. Open calendar', '{date}. فتح التقويم'],
  'format.chooseMonth': ['{date}. Choose month', '{date}. اختر الشهر'],
  'format.updatedMin': ['Updated {count} min ago', 'تم التحديث منذ {count} د'],
  'format.updatedHour': ['Updated {count} hour ago', 'تم التحديث منذ {count} س'], 'format.updatedHoursLong': ['Updated {count} hours ago', 'تم التحديث منذ {count} س'],
  'format.lastSync': ['Last sync {date}', 'آخر مزامنة {date}'],
  'range.withinLower': ['within range', 'ضمن النطاق'], 'range.belowLower': ['below range', 'أقل من النطاق'], 'range.aboveLower': ['above range', 'أعلى من النطاق'],
  'recovery.signalWithin': ['{metric} was within your recent range.', 'كان {metric} ضمن نطاقك المعتاد مؤخرًا.'],
  'recovery.signalBelow': ['{metric} was below your recent range.', 'كان {metric} أقل من نطاقك المعتاد مؤخرًا.'],
  'recovery.signalAbove': ['{metric} was above your recent range.', 'كان {metric} أعلى من نطاقك المعتاد مؤخرًا.'],
  'recovery.sleepShorter': ['Sleep was shorter than your recent range.', 'كان النوم أقصر من نطاقك المعتاد مؤخرًا.'],
  'recovery.sleepLonger': ['Sleep was longer than your recent range.', 'كان النوم أطول من نطاقك المعتاد مؤخرًا.'],
  'recovery.signalLearning': ['{metric} baseline is still learning.', 'ما زلنا نتعلم خط الأساس لـ {metric}.'],
  'recovery.signalUnavailable': ['{metric} baseline is unavailable from this source.', 'لا يتوفر خط أساس لـ {metric} من هذا المصدر.'],
  'recovery.signalMissing': ['{metric} is unavailable today.', '{metric} غير متاح اليوم.'],
  'recovery.signalInvalid': ['{metric} contained invalid values and was excluded.', 'تضمن {metric} قيمًا غير صالحة واستُبعد.'],
  'insight.increased': ['{metric} increased', 'ارتفع {metric}'], 'insight.decreased': ['{metric} decreased', 'انخفض {metric}'],
  'insight.stayedBelow': ['{metric} has stayed below your recent range', 'ظل {metric} أقل من نطاقك المعتاد'],
  'insight.stayedAbove': ['{metric} has stayed above your recent range', 'ظل {metric} أعلى من نطاقك المعتاد'],
  'insight.sleepShort': ['Sleep has stayed shorter than your recent range', 'ظل النوم أقصر من نطاقك المعتاد'],
  'insight.streakBelow': ['{metric} was below its personal typical range for {count} consecutive recorded days.', 'كان {metric} أقل من نطاقه المعتاد في أيام مسجلة متتالية، عددها {count}.'],
  'insight.streakAbove': ['{metric} was above its personal typical range for {count} consecutive recorded days.', 'كان {metric} أعلى من نطاقه المعتاد في أيام مسجلة متتالية، عددها {count}.'],
  'insight.sleepStreak': ['Sleep was shorter than its personal typical range for {count} consecutive recorded days.', 'كان النوم أقصر من نطاقه المعتاد في أيام مسجلة متتالية، عددها {count}.'],
  'insight.sleepHigher': ['Average sleep was {amount} minutes higher than the previous {days} days.', 'كان متوسط النوم أطول بـ {amount} د مقارنةً بالأيام السابقة: {days}.'],
  'insight.sleepLower': ['Average sleep was {amount} minutes lower than the previous {days} days.', 'كان متوسط النوم أقصر بـ {amount} د مقارنةً بالأيام السابقة: {days}.'],
  'insight.hrvHigher': ['Median HRV was {amount}% higher than the previous period.', 'كان وسيط HRV أعلى بـ {amount}% من الفترة السابقة.'],
  'insight.hrvLower': ['Median HRV was {amount}% lower than the previous period.', 'كان وسيط HRV أقل بـ {amount}% من الفترة السابقة.'],
  'insight.rhrHigher': ['Average resting heart rate was {amount} bpm higher than the previous period.', 'كان متوسط نبض الراحة أعلى بـ {amount} bpm من الفترة السابقة.'],
  'insight.rhrLower': ['Average resting heart rate was {amount} bpm lower than the previous period.', 'كان متوسط نبض الراحة أقل بـ {amount} bpm من الفترة السابقة.'],
  'insight.stepsHigher': ['Average steps were {amount} higher than the previous period.', 'كان متوسط الخطوات أعلى بـ {amount} من الفترة السابقة.'],
  'insight.stepsLower': ['Average steps were {amount} lower than the previous period.', 'كان متوسط الخطوات أقل بـ {amount} من الفترة السابقة.'],
  'insight.recoveryHigher': ['Average Recovery was {amount} points higher than the previous period.', 'كان متوسط التعافي أعلى بـ {amount} نقطة من الفترة السابقة.'],
  'insight.recoveryLower': ['Average Recovery was {amount} points lower than the previous period.', 'كان متوسط التعافي أقل بـ {amount} نقطة من الفترة السابقة.'],
  'insight.consistencyMore': ['Bedtime became more consistent', 'أصبح وقت النوم أكثر انتظامًا'],
  'insight.consistencyLess': ['Bedtime became less consistent', 'أصبح وقت النوم أقل انتظامًا'],
  'insight.variationLower': ['Typical bedtime variation was {amount} minutes lower than the previous period.', 'كان الاختلاف المعتاد في وقت النوم أقل بـ {amount} د من الفترة السابقة.'],
  'insight.variationHigher': ['Typical bedtime variation was {amount} minutes higher than the previous period.', 'كان الاختلاف المعتاد في وقت النوم أعلى بـ {amount} د من الفترة السابقة.'],
  'insight.outside': ['{count} days outside your usual range', 'أيام خارج نطاقك المعتاد: {count}'],
  'insight.moreConsistent': ['{amount} min more consistent', 'أكثر انتظامًا بفارق {amount} د'], 'insight.lessConsistent': ['{amount} min less consistent', 'أقل انتظامًا بفارق {amount} د'],
  'consistency.stable': ['Bedtime consistency was stable versus the previous period', 'انتظام أوقات النوم مستقر مقارنةً بالفترة السابقة'],
  'consistency.more': ['Bedtime was more consistent by {amount} minutes', 'وقت النوم أكثر انتظامًا بفارق {amount} د'],
  'consistency.less': ['Bedtime was less consistent by {amount} minutes', 'وقت النوم أقل انتظامًا بفارق {amount} د'],
  'notification.channel': ['Daily health summary', 'ملخص الصحة اليومي'],
  'notification.channelHelp': ['A calm daily reminder to review your locally stored health summary.', 'تذكير يومي هادئ لمراجعة ملخص الصحة المحفوظ محليًا.'],
  'notification.body': ["Review today's health summary.", 'راجع ملخص صحتك اليوم.'],
  'range.7d': ['7D', '٧ أيام'], 'range.30d': ['30D', '٣٠ يومًا'], 'range.90d': ['90D', '٩٠ يومًا'],
  'calendar.recorded': ['recorded day', 'يوم مسجل'], 'calendar.empty': ['no readings', 'لا توجد قراءات'],
  'format.viewDetails': ['{name}. View details', '{name}. عرض التفاصيل'],
  'chart.leftAxis': ['left axis', 'المحور الأيسر'], 'chart.rightAxis': ['right axis', 'المحور الأيمن'],
  'format.activityA11y': ['Daily activity. {readings}', 'النشاط اليومي. {readings}'],
  'format.sleepA11y': ['Sleep composition. {stages}', 'مراحل النوم. {stages}'],
  'format.stageMinutes': ['{stage} {amount} minutes', '{stage} {amount} د'],
  'state.refreshNeeded': ['Refresh needed', 'يلزم التحديث'], 'state.refreshUnavailable': ['Refresh unavailable', 'التحديث غير متاح'],
  'state.yesterday': ['Yesterday', 'أمس'],
  'common.viewDetailsShort': ['View details', 'عرض التفاصيل'],
  'state.emptyHistory': ['Your local database has earlier health data available.', 'يوجد سجل صحي سابق محفوظ على هذا الجهاز.'],
  'state.beforeSync': ['Health data will appear here after your first successful sync.', 'تظهر بيانات الصحة بعد أول مزامنة ناجحة.'],
  'state.conservativeInsights': ['Recent patterns have not crossed the conservative insight thresholds.', 'لم تتجاوز الأنماط الأخيرة حدود التغير المحافظة للملاحظات.'],
  'format.inputs': ['{count}% inputs', '{count}% من المدخلات'],
  'format.appliedWeightDetail': ['{count}% applied weight', '{count}% وزن مطبق'],
  'format.availableDays': ['{available} of {expected} days', '{available} من {expected} أيام'],
  'common.averageLower': ['average', 'متوسط'], 'common.medianLower': ['median', 'وسيط'],
  'format.minutes': ['{amount} min', '{amount} د'],
  'state.noRecentPattern': ['Recent patterns have not crossed conservative personal-change thresholds.', 'لم تتجاوز الأنماط الأخيرة حدود التغير الشخصي المحافظة.'],
} as const;

export type TranslationKey = keyof typeof messages;
export type AppLanguage = 'en' | 'ar';
export const en = Object.fromEntries(Object.entries(messages).map(([key, value]) => [key, value[0]])) as Record<TranslationKey, string>;
export const ar = Object.fromEntries(Object.entries(messages).map(([key, value]) => [key, value[1]])) as Record<TranslationKey, string>;
